# Generated by Django 4.0.5 on 2022-06-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='save_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=16)),
                ('md5_hash', models.CharField(max_length=32, null=True)),
                ('sha256_hash', models.CharField(max_length=64, null=True)),
                ('sha224_hash', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
